apiVersion: v1
kind: Namespace
metadata:
  name: vedec-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
  namespace: vedec-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: ghcr.io/ogrodje/elasticsearch:latest
          ports: [ { containerPort: 9200 } ]

          env:
            - { name: ELASTICSEARCH_USERNAME, value: "elastic" }
            - { name: ELASTICSEARCH_ENABLE_SECURITY, value: "true" }
            - { name: ELASTICSEARCH_SKIP_TRANSPORT_TLS, value: "true" }
            - { name: ELASTICSEARCH_ENABLE_REST_TLS, value: "false" }
            - { name: XPACK_SECURITY_ENABLED, value: "true" }
            - { name: SERVER_SSL_ENABLED, value: "false" }
            - { name: XPACK_MONITORING_ENABLED, value: "false" }
            - { name: "discovery.type", value: "single-node" }
            - { name: "http.cors.enabled", value: "true" }
            - { name: "http.cors.allow-origin", value: "*" }
            - { name: "http.cors.allow-credentials", value: "true" }

            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef: { name: vedec-secret, key: elastic_password }


          resources:
            limits:
              memory: "2Gi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vedec-server
  namespace: vedec-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vedec-server
  template:
    metadata:
      labels:
        app: vedec-server
    spec:
      containers:
        - name: vedec-server
          image: ghcr.io/ogrodje/vedec:latest
          args: [ "server",
                  "-P", "$(PORT)",
                  "--elasticSearchURL", "http://es:9200",
                  "--elasticSearchPassword", "$(ELASTICSEARCH_PASSWORD)",
                  "--hygraphURL", "$(HYGRAPH_URL)" ]
          ports: [ { containerPort: 4441 } ]
          env:
            - name: PORT
              value: "4441"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef: { name: vedec-secret, key: elastic_password }
            - name: HYGRAPH_URL
              valueFrom:
                secretKeyRef: { name: vedec-secret, key: hygraph_url }
          resources:
            limits:
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: vedec-prod
spec:
  selector:
    app: es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: vedec-server
  namespace: vedec-prod
spec:
  selector:
    app: vedec-server
  ports:
    - protocol: TCP
      port: 4441
      targetPort: 4441
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vedec-index-job
  namespace: vedec-prod
spec:
  schedule: "0 */10 * * *"  # Run every 10 hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: vedec-index
        spec:
          containers:
            - name: vedec-index
              image: ghcr.io/ogrodje/vedec:latest
              args: [ "index",
                      "-P", "4441",
                      "--elasticSearchURL", "http://es:9200",
                      "--elasticSearchPassword", "$(ELASTICSEARCH_PASSWORD)",
                      "--hygraphURL", "$(HYGRAPH_URL)" ]
              env:
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: vedec-secret
                      key: elastic_password
                - name: HYGRAPH_URL
                  valueFrom:
                    secretKeyRef:
                      name: vedec-secret
                      key: hygraph_url
          restartPolicy: Never
      backoffLimit: 4
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vedec-prod-ingress
  namespace: vedec-prod
  labels:
    version: "1"
  annotations: { }
  #nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: search.ogrodje.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vedec-server
                port:
                  number: 4441