services:

  es:
    build:
      context: .
      dockerfile: ./docker/es.Dockerfile
    image: ghcr.io/ogrodje/elasticsearch:latest
    container_name: vedec-es
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_ENABLE_SECURITY=true
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_ENABLE_REST_TLS=false
      - XPACK_SECURITY_ENABLED=true
      - SERVER_SSL_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - discovery.type=single-node
      - http.cors.enabled=true
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.ml.enabled=true
      - xpack.graph.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.authc.providers=[]
      - http.cors.allow-origin=*
      - http.cors.allow-methods=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    deploy:
      resources:
        limits:
          memory: 2g

    healthcheck:
      test: [ "CMD-SHELL", "curl -u \"elastic:$ELASTICSEARCH_PASSWORD\" -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      retries: 10

  vedec:
    image: ghcr.io/ogrodje/vedec
    environment:
      PORT: 4441
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      HYGRAPH_URL: ${HYGRAPH_URL}

    command: [ "server",
               "-P", "4441",
               "--elasticSearchURL", "http://es:9200",
               "--elasticSearchPassword", "$ELASTICSEARCH_PASSWORD",
               "--hygraphURL", "$HYGRAPH_URL" ]
    depends_on:
      - es

  vedec-index:
    image: ghcr.io/ogrodje/vedec
    environment:
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      HYGRAPH_URL: ${HYGRAPH_URL}
    command: [ "index",
               "-P", "4441",
               "--elasticSearchURL", "http://es:9200",
               "--elasticSearchPassword", "$ELASTICSEARCH_PASSWORD",
               "--hygraphURL", "$HYGRAPH_URL" ]
    depends_on:
      - es