services:
  es:
    volumes:
      - esdata:/bitnami/elasticsearch/data
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"

  vedec:
    ports:
      - "0.0.0.0:4441:4441"

  kibana:
    container_name: vedec-kibana
    image: bitnami/kibana:latest
    depends_on:
      - es
    ports:
      - "0.0.0.0:5601:5601"
    environment:
      - KIBANA_ELASTICSEARCH_URL=es
      - KIBANA_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_CREATE_USER=yes
      - KIBANA_PASSWORD=${ELASTICSEARCH_PASSWORD}

    healthcheck:
      test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'" ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - kibanadata:/bitnami/kibana

volumes:
  esdata:
    driver: "local"
    driver_opts:
      type: none
      device: /Users/oto/ServiceData/vedec-es
      o: bind
  kibanadata:
    driver: "local"
    driver_opts:
      type: none
      device: /Users/oto/ServiceData/vedec-kibana
      o: bind
